= CloudBees action: Scan Amazon S3 buckets with TruffleHog

Use this action to scan Amazon Simple Storage Service (Amazon S3) buckets with TruffleHog, an open-source secret scanning tool to detect secrets and sensitive information.

== Prerequisites

This action requires prior authentication to Amazon Web Services (AWS), so you must invoke the AWS authentication action before invoking the TruffleHog S3 scan action. 
For more information, refer to link:https://github.com/cloudbees-io/configure-aws-credentials[the AWS credentials configuration action].

== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required
| Description

| `bucket-name`
| string
| Yes
| Name of the S3 bucket.

| `threshold-very-high`
| integer
| No
| The number threshold of very high severity vulnerabilities at which the build is broken.

|===

== Usage examples

In your YAML file, add:

[source,yaml]
----
      - name: Configure AWS credentials
        uses: cloudbees-io/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Run TruffleHog S3 scan
        uses: cloudbees-io/trufflehog-secret-scan-s3@v1
        with:
          bucket-name: "test-bucket"
----

In the following example, if there are more than three very high severity vulnerabilities identified, the build is broken.

[source,yaml]
----

      - name: Run TruffleHog S3 scan with threshold
        uses: cloudbees-io/trufflehog-secret-scan-s3@v1
        with:
          bucket-name: "test-bucket"
          threshold-very-high: 3
----

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/actions[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/[the CloudBees platform].
